"""empty message

Revision ID: 1e873ff46c2e
Revises: 78df8c768afd
Create Date: 2023-03-24 14:38:07.357293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e873ff46c2e'
down_revision = '78df8c768afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_data', schema=None) as batch_op:
        batch_op.alter_column('user_agent_string',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=800),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_data', schema=None) as batch_op:
        batch_op.alter_column('user_agent_string',
               existing_type=sa.String(length=800),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
