"""empty message

Revision ID: 3f9b7c03df4e
Revises: f613095b9010
Create Date: 2023-03-25 04:21:32.597499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f9b7c03df4e'
down_revision = 'f613095b9010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yt_size_mb', sa.Integer(), nullable=True))
        batch_op.drop_column('yt_size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yt_size', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('yt_size_mb')

    # ### end Alembic commands ###
