"""empty message

Revision ID: 78df8c768afd
Revises: 0d1272ac331f
Create Date: 2023-03-24 14:26:26.210038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78df8c768afd'
down_revision = '0d1272ac331f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browser_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('browser_version', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('os_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('os_version', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('device_family', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_agent_string', sa.String(length=100), nullable=True))
        batch_op.drop_column('version')
        batch_op.drop_column('language')
        batch_op.drop_column('browser')
        batch_op.drop_column('platform')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('browser', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('language', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('version', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('user_agent_string')
        batch_op.drop_column('device_type')
        batch_op.drop_column('device_family')
        batch_op.drop_column('os_version')
        batch_op.drop_column('os_type')
        batch_op.drop_column('browser_version')
        batch_op.drop_column('browser_type')

    # ### end Alembic commands ###
