"""empty message

Revision ID: cc6509aeed0e
Revises: 1e873ff46c2e
Create Date: 2023-03-24 14:46:56.023564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc6509aeed0e'
down_revision = '1e873ff46c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_data', schema=None) as batch_op:
        batch_op.alter_column('yt_size',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_data', schema=None) as batch_op:
        batch_op.alter_column('yt_size',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
