"""empty message

Revision ID: f613095b9010
Revises: cc6509aeed0e
Create Date: 2023-03-24 14:56:20.320595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f613095b9010'
down_revision = 'cc6509aeed0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('visit_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_data', schema=None) as batch_op:
        batch_op.drop_column('visit_date')

    with op.batch_alter_table('download_data', schema=None) as batch_op:
        batch_op.drop_column('download_date')

    # ### end Alembic commands ###
